import {
  Si3M,
  SiAbstract,
  SiAdobe,
  SiAirtable,
  SiAmazon,
  SiBmw,
  SiBox,
  SiBuildkite,
  SiBurton,
  SiBytedance,
  SiChase,
  SiCloudbees,
  SiCouchbase,
  SiDailymotion,
  SiDeliveroo,
  SiEpicgames,
  SiGenius,
  SiGodaddy,
  SiHeroku,
  SiNike,
} from "react-icons/si";
import hero from "./assets/hero.jpeg";
import logo from "./assets/logo.png";
import {
  Amex,
  Mastercard,
  Unionpay,
  Visa,
} from "react-payment-logos/dist/flat";

const storename = `Deals4Deals`;
const emailsup = `support@${storename.toLowerCase()}.shop`;
const emailcontact = `contact@${storename.toLowerCase()}.shop`;
const phone = `+1 984 362 0416`;
const address = `25 Arana Cir, Sausalito, CA 94965, United States`;
export const imageTagname = "Variant Image";
export const priceTag = `$`;
export const home = {
  storeName: storename,
  logo: logo,
  headLinks: [
    {
      name: `Home`,
      path: `/`,
    },
    {
      name: `Catalog`,
      path: `/catalog`,
    },
    {
      name: `Contact Us`,
      path: `/contact-us`,
    },
    {
      name: `Order Status`,
      path: `/order-status`,
    },
  ],
  headAction: [
    // {
    //   name: `Buy Now`,
    //   path: `/catalog`,
    // },
    {
      name: `CART`,
      path: `/cart`,
    },
  ],
  hero: {
    heroimg: hero,
    title: `Biggest Q4 Clearance Sale - Up to <span class="text-red-500">70%</span> Off!`,
    description: `Discover incredible deals at ${storename}! As we clear out our inventory for the new year, enjoy discounts of up to 70% on almost everything in the store. Don't miss out on these limited-time offers – shop now and save big!`,
    button: {
      name: `Shop Now`,
      path: `/catalog`,
    },
  },
  brands: {
    top: [
      Si3M,
      SiAbstract,
      SiAdobe,
      SiAirtable,
      SiAmazon,
      SiBmw,
      SiBox,
      SiBuildkite,
      SiBurton,
      SiBytedance,
    ],
    bottom: [
      SiChase,
      SiCloudbees,
      SiCouchbase,
      SiDailymotion,
      SiDeliveroo,
      SiEpicgames,
      SiGenius,
      SiGodaddy,
      SiHeroku,
      SiNike,
    ],
  },
  rating: [
    {
      tempId: 0,
      testimonial: `The fish love it! My tank has never been healthier.`,
      by: `Andre`,
      imgSrc: `https://randomuser.me/api/portraits/men/83.jpg`,
    },
    {
      tempId: 1,
      testimonial: `Best fish food on the market. Highly recommend!`,
      by: `Stephanie`,
      imgSrc: `https://randomuser.me/api/portraits/women/84.jpg`,
    },
    {
      tempId: 2,
      testimonial: `Great variety and my fish can't get enough of it.`,
      by: `Fernando`,
      imgSrc: `https://randomuser.me/api/portraits/men/85.jpg`,
    },
    {
      tempId: 3,
      testimonial: `My fish are healthier and more vibrant than ever.`,
      by: `Marie`,
      imgSrc: `https://randomuser.me/api/portraits/women/86.jpg`,
    },
    {
      tempId: 4,
      testimonial: `If I could give 11 stars, I'd give 12. Best fish food ever!`,
      by: `Andre`,
      imgSrc: `https://randomuser.me/api/portraits/men/87.jpg`,
    },
    {
      tempId: 5,
      testimonial: `So happy we found this fish food! Our tank has never been cleaner.`,
      by: `Marina`,
      imgSrc: `https://randomuser.me/api/portraits/women/88.jpg`,
    },
    {
      tempId: 6,
      testimonial: `Took some convincing, but now my fish tank looks amazing.`,
      by: `Jack`,
      imgSrc: `https://randomuser.me/api/portraits/men/89.jpg`,
    },
    {
      tempId: 7,
      testimonial: `Would be lost without this fish food. The ROI is easily 100X for us.`,
      by: `Daniela`,
      imgSrc: `https://randomuser.me/api/portraits/women/90.jpg`,
    },
    {
      tempId: 8,
      testimonial: `It's just the best fish food. Period.`,
      by: `Fernando`,
      imgSrc: `https://randomuser.me/api/portraits/men/91.jpg`,
    },
    {
      tempId: 9,
      testimonial: `I switched 5 years ago and never looked back. Excellent product!`,
      by: `Sofie`,
      imgSrc: `https://randomuser.me/api/portraits/women/92.jpg`,
    },
    {
      tempId: 10,
      testimonial: `I've been searching for great fish food for years. So glad I found this one!`,
      by: `Pete`,
      imgSrc: `https://randomuser.me/api/portraits/men/93.jpg`,
    },
    {
      tempId: 11,
      testimonial: `It's so simple and intuitive, even my kids can feed the fish with it.`,
      by: `Marina`,
      imgSrc: `https://randomuser.me/api/portraits/women/94.jpg`,
    },
  ],
  footer: {
    items: [
      {
        head: `OUR CUSTOMER`,
        subitems: [
          { name: `Home`, path: `/` },
          { name: `Catalog`, path: `/catalog` },
          { name: `Contact Us`, path: `/contact-us` },
          { name: `Order Status`, path: `/order-status` },
        ],
      },
      {
        head: `OUR POLICY`,
        subitems: [
          // { name: `Search`, path: `/catalog` },
          { name: `Contact Information`, path: `/contact-information` },
          { name: `Privacy Policy`, path: `/privacy-policy` },
          { name: `Refund Policy`, path: `/refund-policy` },
          { name: `Shipping Policy`, path: `/shipping-policy` },
          { name: `Terms of Service`, path: `/terms-of-service` },
        ],
      },
      {
        head: `GOT A QUESTION ?`,
        subitems: [
          {
            name: `📍 ${address}`,
            path: `/contact-us`,
          },
          { name: `☏ ${phone}`, path: `/contact-us` },
          { name: `✉️ ${emailcontact}`, path: `/contact-us` },
        ],
      },
    ],
    subfooter: [
      {
        label: "ms",
        icon: Mastercard,
      },
      {
        label: "ms",
        icon: Visa,
      },
      {
        label: "ms",
        icon: Amex,
      },
      {
        label: "ms",
        icon: Unionpay,
      },
    ],
  },
  contactus: {
    title: `Need To Get In Touch?`,
    adrs: `Our address is ${address}`,
    phonetitle: `Phone Numbers (10 AM to 6 PM EST)`,
    phonesubtitle: `ONLINE ORDER SUPPORT:`,
    phone: phone,
    email: emailcontact,
  },
  pp: [
    `is Privacy Policy describes how your personal information is collected, used, and shared when you visit or make a purchase.`,
    `PERSONAL INFORMATION WE COLLECT`,
    `When you visit the Site, we automatically collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies that are installed on your device. Additionally, as you browse the Site, we collect information about the individual web pages or products that you view, what websites or search terms referred you to the Site, and information about how you interact with the Site. We refer to this automatically collected information as “Device Information.”`,
    `We collect Device Information using the following technologies:`,
    ` - “Cookies” are data files that are placed on your device or computer and often include an anonymous unique identifier. For more information about cookies, and how to disable cookies, visit http://www.allaboutcookies.org.`,
    ` – “Log files” track actions occurring on the Site, and collect data including your IP address, browser type, Internet service provider, referring/exit pages, and date/time stamps.`,
    ` – “Web beacons,” “tags,” and “pixels” are electronic files used to record information about how you browse the Site.`,
    `Additionally when you make a purchase or attempt to make a purchase through the Site, we collect certain information from you, including your name, billing address, shipping address, payment information (including credit card numbers, email address, and phone number. We refer to this information as “Order Information.”`,
    `When we talk about “Personal Information” in this Privacy Policy, we are talking both about Device Information and Order Information.`,
    `How Do We Use Your Personal Information?`,
    `We use the Order Information that we collect generally to fulfill any orders placed through the Site (including processing your payment information, arranging for shipping, and providing you with invoices and/or order confirmations). Additionally, we use this Order Information to: `,
    ` – Communicate with you`,
    ` – Screen our orders for potential risk or fraud`,
    ` – When in line with the preferences you have shared with us, provide you with information or advertising relating to our products or services`,
    `We use the Device Information that we collect to help us screen for potential risk and fraud (in particular, your IP address), and more generally to improve and optimize our Site (for example, by generating analytics about how our customers browse and interact with the Site, and to assess the success of our marketing and advertising campaigns).`,
    `SHARING YOUR PERSONAL INFORMATION`,
    `We share your Personal Information with third parties to help us use your Personal Information, as described above. For example, we use Google Analytics to help us understand how our customers use the Site -- you can read more about how Google uses your Personal Information here: https://www.google.com/intl/en/policies/privacy/. You can also opt-out of Google Analytics here: https://tools.google.com/dlpage/gaoptout.`,
    `Finally, we may also share your Personal Information to comply with applicable laws and regulations, to respond to a subpoena, search warrant or other lawful request for information we receive, or to otherwise protect our rights.`,
    `BEHAVIOURAL ADVERTISING`,
    `As described above, we use your Personal Information to provide you with targeted advertisements or marketing communications we believe may be of interest to you. For more information about how targeted advertising works, you can visit the Network Advertising Initiative’s (“NAI”) educational page at http://www.networkadvertising.org/understanding-online-advertising/how-does-it-work.`,
    `You can opt out of targeted advertising by:`,
    `INCLUDE OPT-OUT LINKS FROM WHICHEVER SERVICES BEING USED.`,
    `COMMON LINKS INCLUDE:`,
    ` – Google: https://www.google.com/settings/u/0/ads/authenticated`,
    ` – Bing: https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads`,
    ` – Facebook: https://www.facebook.com/settings?tab=ads`,
    `Additionally, you can opt out of some of these services by visiting the Digital Advertising Alliance’s opt-out portal at: http://optout.aboutads.info/.`,
    `DO NOT TRACK`,
    `Please note that we do not alter our Site’s data collection and use practices when we see a Do Not Track signal from your browser.`,
    `DATA RETENTION`,
    `When you place an order through the Site, we will maintain your Order Information for our records unless and until you ask us to delete this information.`,
    `CHANGES`,
    `We may update this privacy policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal or regulatory reasons.`,
    `WHAT DO WE DO WITH YOUR INFORMATION?`,
    `When you purchase something from our store, as part of the buying and selling process, we collect the personal information you give us such as your name, address and email address.`,
    `When you browse our store, we also automatically receive your computer’s internet protocol (IP) address in order to provide us with information that helps us learn about your browser and operating system.`,
    `Email marketing (if applicable): With your permission, we may send you emails about our store, new products and other updates.`,
    `Text marketing (if applicable): With your permission, we may send text messages about our store, new products, and other updates. Updates include Checkout Reminders. Webhooks will be used to trigger the Checkout Reminders messaging system.`,
  ],
  refund: [
    `* Must be Within 30 Days of Purchase`,
    `* 15% Restocking Fee May Be Applicable`,
    `* Must be in New, Unused Condition`,
    `* Must be in original packaging with no markings on the product or packaging`,
    `* Customer is Responsible for Outbound & Return Shipping Charges`,
    `* Original outbound shipping & handling fee are non-refundable`,
    `${storename} Shops will accept a return on most items that are in new, unused/unopened condition within 30 days of purchase for a refund, less any shipping and handling charges and a 15% restocking fee If applicable.`,
    `To initialize a return contact ${emailsup}`,
    `Any Issues with Products under Warranty Except Robotic Pool Cleaners are not done through ${storename} Shops. Manufacturers require the customer to contact Them about warranties not the seller.`,
    `IT IS HIGHLY RECOMMENDED THAT CUSTOMER’S USE A SHIPPING METHOD THAT HAS TRACKING CAPABILITY WHEN RETURNING AN ITEM.`,
  ],
  shippingPolicy: [
    `This policy is applicable to (UK) orders. This policy is designed to ensure that you are clearly aware of our shipping policies and procedures. By ordering from this store you accept the policies contained herein.`,
    `SHIPPING CHARGE`,
    `Standard Shipping Cost: FREE`,
    `ORDER CUT OFF TIME AND TIME ZONE`,
    `Order cut off time will be 08:00 PM Pacific Standard Time (London).`,
    `ORDER HANLING TIME`,
    `Order Handling Time: 1 to 2 Business Days (Monday to Friday)`,
    `ORDER TRANSIT TIME`,
    `Order Transit Time: 7 to 15 Business Days (Monday to Friday)`,
    `DELIVERY TERMS`,
    `We use the USPS to deliver the product.`,
    `CHANGE OF ADDRESS`,
    `We cannot change the delivery address once it is in transit. If you need to change the place to deliver your order, please contact us within 24 hours of placing your order at ${emailsup}`,
    `CANCELLATIONS`,
    `If you change your mind before you have received your order, we are able to accept cancellations at any time before the order has been dispatched. If an order has already been dispatched, please refer to our refund policy.`,
    `PARCELS DAMAGED IN TRANSIT`,
    `If you find a parcel is damaged in transit, if possible, please reject the parcel from the courier and get in touch with our customer service. If the parcel has been delivered without you being present, please contact customer service with the next steps.`,
  ],
  tos: [
    `1. ELIGIBILITY, REGISTRATION AND ACCOUNT`,
    `In consideration of your use of the Sites, you agree to (a) provide accurate, current and complete information; (b) maintain and promptly update your account information; (c) maintain the security of your account credentials; (d) not share your account credentials with others; and (e) promptly notify ${storename} Shops if you discover or otherwise suspect any security breaches related to your account or the Sites.`,
    `2. OWNERSHIP OF SITE CONTENT`,
    `You are granted a limited, nonexclusive, non-sublicensable license to access and use the Sites and Site Content for your own personal, non-commercial use. Such license is subject to your compliance with these Terms and does not include the right to engage in: (a) any resale or commercial use of the Sites or Site Content; (b) the collection and use of any product listings, pictures or descriptions; (c) the distribution, public performance or public display of any Site Content; (d) modifying or otherwise making any derivative uses of the Sites and the Site Content, or any portion thereof; (e) use of any data mining, robots or similar data gathering or extraction methods; (f) downloading (other than page caching) of any portion of the Sites, the Site Content or any information contained therein, except as expressly permitted on the Sites or pursuant to separate terms; or (g) any use of the Sites or the Site Content other than for their intended purposes. Any use of the Sites or the Site Content outside the scope of the license granted herein, without the prior written permission of ${storename} SHOPS, is strictly prohibited and will result in automatic termination of the license granted herein. Such prohibited use in violation of the license granted may also violate applicable laws, including but not limited to copyright and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in these Terms shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise. This license is revocable at any time at ${storename} SHOP’s sole discretion.`,
    `3. REPEAT INFRINGER POLICY; COPYRIGHT COMPLAINTS`,
    `In accordance with the Digital Millennium Copyright Act (“DMCA”) and other applicable laws, ${storename} shops has adopted a policy of limiting access by, or terminating the online accounts of users who repeatedly infringe the intellectual property rights of others.`,
    `Please see 17 U.S.C. §512(c)(3) for the requirements of a proper notification. You should also note that if you make any material misrepresentation in your notification that the material or activity is infringing, you will be liable for all damages, including costs and attorneys’ fees, incurred by us or the alleged infringer as the result of our relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing.`,
    `We may give notice of a claim of copyright infringement to our users by means of a general notice on the Sites, electronic mail to a user’s email address in our records or by written communication sent by first-class mail to a user’s address in our records.`,
    `4. HYPERLINKS`,
    `You are granted a limited, non-exclusive right to create a text hyperlink to the Sites for noncommercial purposes, provided such link does not portray ${storename} Shops or any of our products and services in a false, misleading, derogatory or otherwise defamatory manner and provided further that the linking site does not contain any adult or illegal material or any material that is offensive, harassing or otherwise objectionable. This limited right may be revoked at any time. You may not use an ${storename} Shops logo or other proprietary graphic of ${storename} Shops to link to the Sites without the express written permission of ${storename} Shops. Further, you may not use, frame or utilize framing techniques to enclose any ${storename} Shops trademark, logo or other proprietary information, including the images found at the Sites, the content of any text or the layout/design of any page or form contained on a page on the Sites without j akihoShop’s express written consent.`,
    `8. USER CONTENT AND INTERACTIVE AREAS`,
    `The Sites may include discussion forums, blogs, profiles, product reviews or other interactive features or areas (collectively, “Interactive Areas”), in which you or other users can create, post, upload, transmit, distribute or store content, such as comments, reviews, photos, videos, text, music, sound, , graphics, code or other materials on the Sites (collectively, “User Content”). User Content may be publicly-viewable along with profile information associated with your online account, but it does not include your ${storename} Shops account information or information you submit in order to make a purchase. You agree that you are solely responsible for your User Content and for your use of such Interactive Areas, and that you use the Interactive Areas at your own risk.`,
    `By using any Interactive Areas, you agree not to create, post, upload, transmit, distribute, or store any of the following:`,
    `- User Content that is fake, unlawful, libelous, defamatory, obscene, pornographic, indecent, lewd, suggestive, harassing, threatening, abusive, inflammatory, fraudulent or otherwise objectionable;`,
    `- User Content that would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party or that would otherwise create liability or violate any local, state, national or international law;`,
    `- User Content that promotes or encourages the use of trails that are not legally open (except for seasonally closed trails) or trespassing;`,
    `- User Content that displays, describes or encourages usage of any product we sell in a manner that could be offensive, inappropriate or harmful to ${storename} Shops or any user or consumer or that is contrary to any instructions or warnings relating to the product (safety concerns can be reported here);`,
    `- User Content that may impinge upon or violate the publicity, privacy or data protection rights of others, including pictures, videos, images or information about another individual where you have not obtained such individual’s consent;`,
    `- User Content that makes false or misleading statements, claims or depictions about a person, company, product or service;`,
    `- User Content that does not clearly and prominently disclose any material connections you may have to ${storename} Shops or third party brands or sellers (for example, if you receive free products or services or are a paid blogger or employee);`,
    `- User Content that may infringe any patent, trademark, trade secret, copyright or other intellectual or proprietary right of any party;`,
    `- User Content that impersonates any person or entity or otherwise misrepresents your affiliation with a person or entity;`,
    `- User Content that contains viruses, malware of any kind, corrupted data or other harmful, disruptive or destructive files or code; and`,
    `- User Content that, in the sole judgment of ${storename} Shops, restricts or inhibits any other person from using or enjoying the Sites or which may expose ${storename} Shops or our users to any harm or liability of any type.`,
    `${storename} Shops encourages our users to report User Content that violates these Terms (either by using a flagging or reporting mechanism provided within the Sites or, for content that infringes copyright or trademark rights, by following the instructions in Sections 4 and 5 of Part One of these Terms). Enforcement of the Terms, however, is solely in our discretion and the absence of enforcement of these Terms in some instances does not constitute a waiver of our right to enforce the Terms in other instances. In addition, these Terms do not create any private right of action on the part of any third party or any reasonable expectation or promise that the Sites will not contain any content that is prohibited by such Terms. Although ${storename} Shops has no obligation to screen, edit or monitor any of the User Content posted on the Sites, ${storename} Shops reserves the right, and has absolute discretion, to remove, screen or edit any User Content posted or stored on the Sites at any time and for any reason without notice, and you are solely responsible for creating backup copies and replacing any User Content you post or store on the Sites at your sole cost and expense.`,
    `Any use of the Sites in violation of these Terms may result in, among other things, termination or suspension of your rights to use the Interactive Areas and/or the Sites.`,
    `9. RIGHTS IN USER CONTENT`,
    `Except as otherwise provided in these Terms, on the Sites or in a separate agreement with us (such as the rules of an ${storename} Shops contest or an ${storename} Shops content submission agreement), ${storename} Shops claims no ownership or control over any User Content. However, by submitting or posting User Content on the Sites, you grant ${storename} Shops a nonexclusive, royalty-free, world-wide, perpetual, irrevocable, transferable, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, publicly perform and display such User Content on the Sites and on third-party sites and mobile applications and in all other media or formats, whether currently known or hereafter developed, for any purpose and without any compensation to you. Also, if you submit, post or share User Content through the Sites or third-party platforms, you understand that this User Content will be viewable by others.`,
    `By posting User Content to the Sites, you represent and warrant that (a) such User Content is non-confidential; (b) you own and control all of the rights, title and interest in and to the User Content or you otherwise have all necessary rights to post and use such User Content to the Sites and to grant the rights to ${storename} Shops that you grant in these Terms; (c) the User Content is accurate and not misleading or harmful in any manner; and (d) the User Content, and your use and posting thereof in connection with the Sites, do not and will not violate these Terms, or any other applicable  Shops terms, guidelines or policies or any applicable law, rule or regulation.`,
    `10. REVIEWS`,
    `We may provide specific opportunities for you to tell jak ihoShops and other ${storename} Shops members or users what you think about our products or services. You are solely responsible for the reviews you submit and understand that you may not be able to delete this content after it has been published. You also assume all risks associated with your reviews, including anyone’s reliance on the quality, accuracy or reliability of such reviews, and the disclosure of your personal information in connection with such content. If you submit reviews, you agree to state your opinions lawfully, honestly and in good faith and to reveal to others any conflict of interest or relationship that might influence your views (e.g., if someone is paying or giving you something for free to encourage you to comment, you agree to make appropriate disclosures). All reviews are strictly the opinion of the user posting such reviews, and ${storename} Shops does not endorse or approve any such reviews or have any responsibility or liability for the accuracy, appropriateness or content of such reviews. Finally, we may use a third party to “power” or provide the opportunity to provide reviews. In that case, you will also need to review such third party’s terms of service and privacy policy, to determine whether they are acceptable to you. If they are not, do not provide reviews to us using the third party’s service or technology.`,
    `11. FEEDBACK`,
    `Separate and apart from User Content, you have the ability to submit questions, comments suggestions, reviews, ideas, plans, designs, notes, proposals, drawings, original or creative materials and other information regarding the Sites, ${storename} Shops and our products or services (collectively “Feedback”). You agree that Feedback is non-confidential and shall become the sole property of ${storename}  Shops. ${storename} Shops shall own exclusive rights, including all intellectual property rights, in and to such Feedback and shall be entitled to the unrestricted use and dissemination of the Feedback for any purpose, commercial or otherwise, without acknowledgment or compensation to you. Do not send us Feedback if you expect to be paid or want to continue to own or claim rights in them; your idea might be great, but we may have already had the same or a similar idea and we do not want disputes.`,
    `12. PROHIBITED CONDUCT`,
    `Engage in any harassing, intimidating, predatory or stalking conduct;`,
    `Develop or use any third-party applications that interact with User Content or our Sites without our prior written consent;`,
    `Use the Sites in a manner that could interfere with or damage, disable, overburden or impair the operation of the Sites or introduce to the Sites or our users any viruses, malware, corrupted data or other harmful, disruptive or destructive files or code; or`,
    `“Frame” our Sites or otherwise make it look like you have a relationship with us or that we have endorsed you for any purpose.`,
    `${storename} Shops has no obligation to monitor any user conduct on the Sites, but ma sieraShops reserves the right and has absolute discretion to monitor any user conduct on the Sites at any time and for any reason without notice. ${storename} Shops does not approve or endorse any user-posted meetings or events referenced on the Sites and ${storename} Shops recommends exercising caution before contacting or meeting anyone (online or offline) that is unfamiliar to you.`,
    ``,
    `13. NO THIRD-PARTY BENEFICIARIES`,
    `These Terms are for the benefit of, and will be enforceable by, the parties only. These Terms are not intended to confer any right or benefit on any third party or to create any obligations or liability of a party to any such third party.`,
    ``,
    `14. INDEMNIFICATION`,
    `To the fullest extent permitted by applicable law, you agree to defend, indemnify and hold harmless ${storename} Shops and our respective officers, directors, agents, partners, members, employees, independent contractors, service providers and consultants (together with ${storename} Shops, the “${storename} Shops Parties”), from and against any claims, damages, costs, liabilities and expenses (collectively, “Claims”) arising out of or related to (a) your access to and use or misuse of the Sites; (b) any User Content you create, post, upload, use, distribute, store or otherwise transmit on or through the Sites; (c) any Feedback you provide; (d) your violation of these Terms; and (e) your violation, misappropriation or infringement of any rights of another. You agree to promptly notify the ${storename} Shops Parties of any third party Claims, cooperate with the ${storename} Shops Parties in defending such Claims and pay all fees, costs and expenses associated with defending such Claims (including but not limited to attorneys’ fees). You further agree that the ${storename} Shops Parties shall have control of the defense or settlement of any third party Claims.`,
    ``,
    `15. SMS/MMS MOBILE MESSAGE MARKETING PROGRAM TERMS AND CONDITIONS`,
    `${storename} Shops (hereinafter, “We,” “Us,” “Our”) is offering a mobile messaging program (the “Program”), which you agree to use and participate in subject to these Mobile Messaging Terms and Conditions and Privacy Policy [Insert URL Link to your Privacy Policy] (the “Agreement”). By opting in to or participating in any of our Programs, you accept and agree to these terms and conditions, including, without limitation, your agreement to resolve any disputes with us through binding, individual-only arbitration, as detailed in the “Dispute Resolution” section below. This Agreement is limited to the Program and is not intended to modify other Terms and Conditions or Privacy Policy that may govern the relationship between you and Us in other contexts.`,
    `User Opt In: The Program allows Users to receive SMS/MMS mobile messages by affirmatively opting into the Program, such as through online or application-based enrollment forms. Regardless of the opt-in method you utilized to join the Program, you agree that this Agreement applies to your participation in the Program. By participating in the Program, you agree to receive autodialed or prerecorded marketing mobile messages at the phone number associated with your opt-in, and you understand that consent is not required to make any purchase from Us. While you consent to receive messages sent using an autodialer, the foregoing shall not be interpreted to suggest or imply that any or all of Our mobile messages are sent using an automatic telephone dialing system (“ATDS” or “autodialer”). Message and data rates may apply. Message frequency varies.`,
    `User Opt Out: If you do not wish to continue participating in the Program or no longer agree to this Agreement, you agree to reply STOP, END, CANCEL, UNSUBSCRIBE, or QUIT to any mobile message from Us in order to opt out of the Program. You may receive an additional mobile message confirming your decision to opt out. You understand and agree that the foregoing options are the only reasonable methods of opting out. You acknowledge that our text message platform may not recognize and respond to unsubscribe requests that alter, change, or modify the STOP, END, CANCEL, UNSUBSCRIBE or QUIT keyword commands, such as the use of different spellings or the addition of other words or phrases to the command, and agree that ${storename} Shops and its service providers will have no liability for failing to honor such requests. You also understand and agree that any other method of opting out, including, but not limited to, texting words other than those set forth above or verbally requesting one of our employees to remove you from our list, is not a reasonable means of opting out.`,
    `Program Description: Without limiting the scope of the Program, users that opt into the Program can expect to receive messages concerning the marketing, promotion, payment, delivery and sale of [Describe company’s goods/service offerings – this should be broad and general to encompass any type of message you may send. Messages outside of this scope may not be allowed under the TCPA]. Messages may include checkout reminders.`,
    `Cost and Frequency: Message and data rates may apply. You agree to receive messages periodically at Our discretion. Daily, weekly, and monthly message frequency will vary. The Program involves recurring mobile messages, and additional mobile messages may be sent periodically based on your interaction with Us.`,
    `Support Instructions: For support regarding the Program, text “HELP” to the number you received messages from or email us at sneif3@gmail.com. Please note that the use of this email address is not an acceptable method of opting out of the program. Opt outs must be submitted in accordance with the procedures set forth above.`,
    `MMS Disclosure: The Program will send SMS TMs (terminating messages) if your mobile device does not support MMS messaging.`,
    `Our Disclaimer of Warranty: The Program is offered on an “as-is” basis and may not be available in all areas at all times and may not continue to work in the event of product, software, coverage or other changes made by your wireless carrier. We will not be liable for any delays or failures in the receipt of any mobile messages connected with this Program. Delivery of mobile messages is subject to effective transmission from your wireless service provider/network operator and is outside of Our control. Carriers are not liable for delayed or undelivered mobile messages.`,
    `Participant Requirements: You must have a wireless device of your own, capable of two-way messaging, be using a participating wireless carrier, and be a wireless service subscriber with text messaging service. Not all cellular phone providers carry the necessary service to participate. Check your phone capabilities for specific text messaging instructions.`,
    `Age Restriction: You may not use or engage with the Platform if you are under thirteen (13) years of age. If you use or engage with the Platform and are between the ages of thirteen (13) and eighteen (18) years of age, you must have your parent’s or legal guardian’s permission to do so. By using or engaging with the Platform, you acknowledge and agree that you are not under the age of thirteen (13) years, are between the ages of thirteen (13) and eighteen (18) and have your parent’s or legal guardian’s permission to use or engage with the Platform, or are of adult age in your jurisdiction. By using or engaging with the Platform, you also acknowledge and agree that you are permitted by your jurisdiction’s Applicable Law to use and/or engage with the Platform.`,
    `Prohibited Content: You acknowledge and agree to not send any prohibited content over the Platform. Prohibited content includes: – Any fraudulent, libelous, defamatory, scandalous, threatening, harassing, or stalking activity; – Objectionable content, including profanity, obscenity, lasciviousness, violence, bigotry, hatred, and discrimination on the basis of race, sex, religion, nationality, disability, sexual orientation, or age; – Pirated computer programs, viruses, worms, Trojan horses, or other harmful code; – Any product, service, or promotion that is unlawful where such product, service, or promotion thereof is received; – Any content that implicates and/or references personal health information that is protected by the Health Insurance Portability and Accountability Act (“HIPAA”) or the Health Information Technology for Economic and Clinical Health Act (“HITEC” Act); and – Any other content that is prohibited by Applicable Law in the jurisdiction from which the message is sent.`,
    `Dispute Resolution: In the event that there is a dispute, claim, or controversy between you and Us, or between you and Stodge Inc. d/b/a Postscript or any other third-party service provider acting on Our behalf to transmit the mobile messages within the scope of the Program, arising out of or relating to federal or state statutory claims, common law claims, this Agreement, or the breach, termination, enforcement, interpretation or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, such dispute, claim, or controversy will be, to the fullest extent permitted by law, determined by arbitration in Morris Plains, New Jersey before one arbitrator. The parties agree to submit the dispute to binding arbitration in accordance with the Commercial Arbitration Rules of the American Arbitration Association (“AAA”) then in effect. Except as otherwise provided herein, the arbitrator shall apply the substantive laws of the Federal Judicial Circuit in which m asieraShops’s principle place of business is located, without regard to its conflict of laws rules. Within ten (10) calendar days after the arbitration demand is served upon a party, the parties must jointly select an arbitrator with at least five years’ experience in that capacity and who has knowledge of and experience with the subject matter of the dispute. If the parties do not agree on an arbitrator within ten (10) calendar days, a party may petition the AAA to appoint an arbitrator, who must satisfy the same experience requirement. In the event of a dispute, the arbitrator shall decide the enforceability and interpretation of this arbitration agreement in accordance with the Federal Arbitration Act (“FAA”). The parties also agree that the AAA’s rules governing Emergency Measures of Protection shall apply in lieu of seeking emergency injunctive relief from a court. The decision of the arbitrator shall be final and binding, and no party shall have rights of appeal except for those provided in section 10 of the FAA. Each party shall bear its share of the fees paid for the arbitrator and the administration of the arbitration; however, the arbitrator shall have the power to order one party to pay all or any portion of such fees as part of a well-reasoned decision. The parties agree that the arbitrator shall have the authority to award attorneys’ fees only to the extent expressly authorized by statute or contract. The arbitrator shall have no authority to award punitive damages and each party hereby waives any right to seek or recover punitive damages with respect to any dispute resolved by arbitration. THE PARTIES AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY VIA ARBITRATION AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ARBITRATION PROCEEDING. Further, unless both parties agree otherwise in a signed writing, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding. Except as may be required by law, neither a party nor the arbitrator may disclose the existence, content, or results of any arbitration without the prior written consent of both parties, unless to protect or pursue a legal right. If any term or provision of this Section is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other term or provision of this Section or invalidate or render unenforceable such term or provision in any other jurisdiction. If for any reason a dispute proceeds in court rather than in arbitration, the parties hereby waive any right to a jury trial. This arbitration provision shall survive any cancellation or termination of your agreement to participate in any of our Programs.`,
    `Florida Law: We endeavor to comply with the Florida Telemarketing Act and the Florida Do Not Call Act as applicable to Florida residents. For purposes of compliance, you agree that we may assume that you are a Florida resident if, at the time of opt-in to Program, (1) your shipping address, as provided is located in Florida or (2) the area code for the phone number used to opt-into the Program is a Florida area code. You agree that the requirements of the Florida Telemarketing Act and the Florida Do Not Call Act do not apply to you, and you shall not assert that you are a Florida resident, if you do not meet either of these criteria or, in the alternative, do not affirmatively advise us in writing that you are a Florida resident by sending written notice to us. Insofar as you are a Florida resident, you agree that mobile messages sent by Us in direct response to mobile messages or requests from You (including but are not limited to response to Keywords, opt-in, help or stop requests and shipping notifications) shall not constitute a “telephonic sales call” or “commercial telephone solicitation phone call” for purposes of Florida Statutes Section 501 (including but not limited to sections 501.059 and 501.616), to the extent the law is otherwise relevant and applicable.`,
    `Miscellaneous: You warrant and represent to Us that you have all necessary rights, power, and authority to agree to these Terms and perform your obligations hereunder, and nothing contained in this Agreement or in the performance of such obligations will place you in breach of any other contract or obligation. The failure of either party to exercise in any respect any right provided for herein will not be deemed a waiver of any further rights hereunder. If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable. Any new features, changes, updates or improvements of the Program shall be subject to this Agreement unless explicitly stated otherwise in writing. We reserve the right to change this Agreement from time to time. Any updates to this Agreement shall be communicated to you. You acknowledge your responsibility to review this Agreement from time to time and to be aware of any such changes. By continuing to participate in the Program after any such changes, you accept this Agreement, as modified.`,
    `16. DISCLAIMERS`,
    `Except as expressly provided, the Sites, Site Content and services provided on or in connection with the Sites (collectively, “Complete Site”) are provided on an “AS IS” and “WITH ALL FAULTS” basis without representations, warranties or conditions of any kind, either express or implied. ${storename} Shops DISCLAIMS ALL OTHER REPRESENTATIONS, WARRANTIES, CONDITIONS AND DUTIES, EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES, DUTIES OR CONDITIONS: (A) OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR USE, RESULTS, TITLE, AND NON-INFRINGEMENT; AND (B) CREATED BY TRADE USAGE, COURSE OF DEALING OR COURSE OF PERFORMANCE. ${storename} Shops does not represent or warrant that the Complete Site is accurate, complete, reliable, current or error-free. ${storename} Shops does not represent or warrant that the Sites or our servers are free of viruses or other harmful components.`,
    `The Site Content, including, but not limited to, ${storename} Shops and third-party photos, videos, articles, information and other content is general in nature and must be used with an appreciation for the differing capabilities among individual users, weather and other varying conditions, and the differing demands placed on equipment or techniques by the wide variety of circumstances that can be encountered in outdoor recreation. The information is not a substitute for in-person guidance by a qualified instructor or for personal experience gained in the company of knowledgeable and experienced outdoor recreationalists. You acknowledge that you could be seriously injured or die when engaging in activities presented on the Sites and that you should receive professional instruction when appropriate. You assume all risks associated with engaging in any activities or using any equipment presented on the Sites.`,
    `You may have the ability to exchange information with other users of the Sites and arrange to meet each other offline. You understand that ${storename} Shops does not conduct background checks of users or otherwise vouch for the safety of such offline meetings, and such meetings are held at your sole risk. You are advised to be careful not to accidentally divulge personal information about yourself, such as your name, phone number or address. We encourage you to take precautions when interacting with other users, particularly when meeting a stranger in person for the first time.`,
    `Our trail condition reporting feature is not an emergency service; if you are facing an emergency or witness an emergency, contact law enforcement or emergency services.`,
    `17. LIMITATION OF LIABILITY`,
    `TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE ${storename} Shops PARTIES BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGES, INCLUDING, BUT NOT LIMITED TO, LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED TO THE ACCESS OR USE OF THE SITES, YOUR ONLINE OR OFFLINE INTERACTIONS WITH OTHER SITE USERS, YOUR PARTICIPATION IN ACTIVITIES, EVENTS, OUTINGS OR EXPERIENCES THAT ARE NOT OFFICIALLY ORGANIZED AND HOSTED BY ma sieraSHOPS OR OTHERWISE RELATED TO THESE TERMS, INCLUDING BUT NOT LIMITED TO ANY DAMAGES THAT RESULT FROM EVENTS BEYOND OUR REASONABLE CONTROL, SUCH AS INTERRUPTIONS TO ALL OR PORTIONS OF THE SITES, DELETION OF FILES OR EMAIL, ERRORS OR OMISSIONS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION OR FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION OR UNAUTHORIZED ACCESS TO AN ${storename} SHOPS PARTY’S RECORDS, PROGRAMS OR SERVICES.`,
    `TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE AGGREGATE LIABILITY OF THE ${storename} Shops PARTIES (JOINTLY), WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), OR OTHER THEORY, ARISING OUT OF OR RELATING TO THE USE OF OR INABILITY TO USE THE COMPLETE SITE EXCEED THE GREATER OF USD $50.00 OR ANY COMPENSATION YOU PAY, IF ANY, TO ${storename} SHOPS FOR ACCESS TO OR USE OF THE COMPLETE SITE. THE LIMITATIONS SET FORTH IN THIS SECTION 16 WILL NOT LIMIT OR EXCLUDE THE ${storename} SHOPS PARTIES’ LIABILITY FOR GROSS NEGLIGENCE, FRAUD, INTENTIONAL, WILLFUL, MALICIOUS OR RECKLESS MISCONDUCT.`,
    `${storename} IS NOT RESPONSIBLE FOR MIS-USE OF CHEMICALS AND ANY DAMAGE RESULTING FROM SAID MIS-USE`,
    `We are responsible for your new purchase until its picked up by the shipping company After that, it is out of our control and we recommend that you select UPS INSURED SHIPPING. Insurance is to protect against loss or damage during shipping. If you choose not to buy insurance and your purchase is lost or damaged by USPS, we cannot provide a refund. All purchases are shipped by UPS or USPS and insured through UPS or USPS.`,
    `In the case that your shipment is lost or damaged in transit; YOU ARE RESPONSIBLE TO FILE THE CLAIM WITH UPS. WE ARE NOT RESPONSIBLE FOR LOST PACKAGES DURING TRANSIT! WE ARE NOT RESPONSIBLE FOR SHIPMENTS SENT TO FORWARDING SERVICES OR COMPANIES REGARDLESS OF SHIPPING SERVICE SELECTED, IF YOU PLACE AN ORDER AND YOUR SHIPPING ADDRESS IS A FORWARDING ADDRESS YOU ARE RESPONSIBLE FOR CONTACTING YOUR FORWARDING COMPANY OR SERVICE TO LOCATE YOUR SHIPMENT`,
    `WE ARE ALSO NOT RESPONSIBLE TO WEATHER RELATED DAMAGE OR DELAYS! ONCE PACKAGE LEAVES OUR HANDS IT IS COMPLETELY OUT OF OUR CONTROL!`,
    `Please make sure your address is correct before placing an order. We will not be responsible for incorrect addresses. Packages are NOT insured, if you would like to purchase insurance for your package please select UPS INSURED SHIPPING. Once again we are not responsible for packages once it transfers to UPS or USPS, it is then their responsibility to deliver and handle concerns for shipping delays or lost packages. You will not be refunded for the purchase from us if UPS or USPS loses the package unless you purchase the additional insurance. KEEP AN EYE ON YOUR PACKAGE'S TRACKING PROGRESS.`,
    `SHIPPING FEES ARE NOT REFUNDABLE: Please make sure all addresses are correct before placing your order, we will not refund shipping fees for wrong addresses on your part or returned shipments. `,
    `18. MODIFICATIONS TO SITES`,
    `${storename} Shops reserves the right to modify or discontinue, temporarily or permanently, the Sites or any features or portions thereof without prior notice.`,
    `19. APPLICABLE LAW AND VENUE`,
    `THESE TERMS AND YOUR ACCESS TO AND USE OF THE SITES WILL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAWS OF THE STATE OF WASHINGTON, APPLICABLE TO AGREEMENTS MADE AND TO BE ENTIRELY PERFORMED WITHIN THE STATE OF WASHINGTON, WITHOUT RESORT TO ITS CONFLICT OF LAW PROVISIONS. YOU AGREE THAT ANY ACTION AT LAW OR IN EQUITY ARISING OUT OF OR RELATING TO THESE TERMS SHALL BE FILED ONLY IN THE STATE AND FEDERAL COURTS LOCATED IN KING COUNTY, WASHINGTON AND YOU HEREBY IRREVOCABLY AND UNCONDITIONALLY CONSENT AND SUBMIT TO THE EXCLUSIVE JURISDICTION OF SUCH COURTS OVER ANY SUIT, ACTION OR PROCEEDING ARISING OUT OF THESE TERMS.`,
    `20. TERMINATION`,
    `You may terminate the Terms at any time by closing your account, discontinuing your use of the Sites and providing ${storename} Shops with a notice of termination. ${storename} Shops reserves the right, without notice and in our sole discretion, to terminate your right to use the Sites, or any portion of the Sites, and to block or prevent your future access to and use of the Sites or any portion of the Sites.`,
    `21. SEVERABILITY`,
    `If any term, clause, or provision of these Terms shall be deemed unlawful, void or for any reason unenforceable, then that term, clause, or provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining terms, clauses, or provisions.`,
    `PART TWO – TERMS OF SALE`,
    `PART TWO APPLIES IN ADDITION TO PART ONE IF YOU PURCHASE A PRODUCT OR SERVICE THROUGH THE SITES.`,
    `1. PRICING AND AVAILABILITY`,
    `All prices are shown in U.S. dollars (except where otherwise noted on certain ${storename} Shops adventure travel trips); taxes, shipping and handling charges are additional. All items are subject to availability and we reserve the right to impose quantity limits on any order, to reject all or part of an order and to discontinue products or services without notice, even if you have already placed your order. All prices are subject to change without notice and you agree that taxes may be adjusted from the amount shown on the billing screens. Several factors may cause this, such as variances between processor programs and changes in tax rates. Additionally, many products displayed on our Sites are also available in ${storename} Shops retail stores while supplies last, but you should not assume that what you see on the Sites can always be seen in our stores. Prices displayed on the Sites may vary from those in the store or from store-advertised prices.`,
    `2. ERRORS`,
    `We attempt to be as accurate as possible and to eliminate errors on the Sites; however, we do not warrant that any product, service, description, photograph, pricing or other information is accurate, complete, reliable, current or error-free. In the event of an error—whether on the Sites, in an order confirmation, in processing an order, in delivering a product or service or otherwise—we reserve the right to correct such error and to revise your order accordingly if necessary (including charging the correct price) or to cancel the order and refund any amount charged. Your sole remedy in the event of such error is to cancel your order and obtain a refund.`,
    `3. OUT-OF-STOCK ITEMS; BACKORDERS`,
    `If the color or size you want is not listed in the “Choose Your Color/Size” drop-down box on the Product Information page, it is not then available for ordering. Please check back later. If the color or size you want has an asterisk next to it in the drop-down box, it is on backorder. Sometimes we will not know in advance that product is unavailable, so when you place items in your Shopping Cart you will be asked if you would like to backorder them. If you indicate yes, the item will be sent to you once it becomes available. Some items may be backordered or unavailable even if the Sites indicate that they are in-stock, and adding an item to your cart does not guarantee the availability of that item. We will not charge your payment card until the item ships to the designated delivery address. If you choose to pick up an item at an ${storename} Shops store, you will be charged at the time you pick up the order. If the backordered item is no longer available, we will cancel the item from your order and notify you, usually via e-mail. If you have items on backorder that you would like to cancel, please contact us.`,
    `4. AGREEMENT TO CONDUCT TRANSACTIONS ELECTRONICALLY; RECORDING; COPIES`,
    `You agree that all of your transactions with or through the Sites may, at our option, be conducted electronically from start to finish, and that any oral conversations may be recorded. If we decide to proceed non-electronically, those transactions will still be governed by the remainder of these Terms unless you enter into different terms provided by us. You are responsible to print or make an electronic copy of these Terms and any other contract or disclosure that we are required to provide to you.`,
  ],
  orderstatus: [
    `Once your order has shipped you will receive an email from us with a tracking number and link to track your order. You can also enter your tracking number in the box below to get the latest status on your shipment.`,
    `Please provide your tracking number (not the order number):`,
  ],
};

// export const productsData = [
//   {
//     id: `A1B2C3D4E5F6`,
//     productName: `Fish Sulfa Forte - Sulfamethoxazole 800 mg, Trimethoprim 160 mg Tablets (30 Count)`,
//     price: `£69.95`,
//     image: `https://${storename}.myshopify.com/cdn/shop/files/SUL_360x.png?v=1718923423`,
//   },
//   {
//     id: `G7H8I9J0K1L2`,
//     productName: `Fish sulfa forte Sulfamethoxazole /Trimethoprim 800mg 100 count`,
//     price: `£69.95`,
//     image: `https://${storename}.myshopify.com/cdn/shop/files/sulfa-1001_360x.jpg?v=1718923468`,
//   },
//   {
//     id: `M3N4O5P6Q7R8`,
//     productName: `fish zithro azithromycin 30 tablets`,
//     price: `£69.95`,
//     image: `https://${storename}.myshopify.com/cdn/shop/files/aquariumazithromycin30_360x.jpg?v=1718923396`,
//   },
//   {
//     id: `S9T0U1V2W3X4`,
//     productName: `Fish Zole Forte - Metronidazole 500 mg (60 Count)`,
//     price: `£89.99`,
//     image: `https://${storename}.myshopify.com/cdn/shop/files/MET30_0a140cf4-8dd9-4856-a085-e9211a0df7ea_360x.png?v=1718923360`,
//   },
//   {
//     id: `Y5Z6A7B8C9D0`,
//     productName: `fish zole forte - Metronidazole 500 mg 100 Tablets`,
//     price: `£89.95`,
//     image: `https://${storename}.myshopify.com/cdn/shop/files/metronidazole-500-100pak_360x.jpg?v=1718923462`,
//   },
// ];
